[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.environment]
NODE_VERSION = "18.20.5"
NIXPACKS_BUILD_CMD = "npm ci --only=production"
NIXPACKS_INSTALL_CMD = "npm ci --only=production"

[build.nixpacks]
startCmd = "npm start"
buildCmd = "npm ci --only=production"
installCmd = "npm ci --only=production"
